export const WEAPONS = [
  {
    id: "pea",
    name: "PEA SHOOTER",
    damage: 14,
    pellets: 1,
    spread: 0,
    range: 16,
    cooldown: 0.2,
    ammoKey: "pea",
    ammoPerShot: 1,
  },
  {
    id: "shotgun",
    name: "CORN SHOTGUN",
    damage: 10,
    pellets: 7,
    spread: 0.18,
    range: 10,
    cooldown: 0.7,
    ammoKey: "corn",
    ammoPerShot: 1,
  },
  {
    id: "launcher",
    name: "COB LAUNCHER",
    damage: 90,
    pellets: 1,
    spread: 0,
    range: 20,
    cooldown: 1.0,
    ammoKey: "cob",
    ammoPerShot: 1,
    splash: 2.2,
    projectile: true,
  },
];
