export const WEAPONS = [
  {
    id: "pea",
    name: "PEA SHOOTER",
    damage: 14,
    count: 1,
    spread: 0.02,
    speed: 14,
    cooldown: 0.22,
    ammoKey: "pea",
    ammoPerShot: 1,
    projectileSprite: "peaBall",
    flashColor: "#b6ff6a",
  },
  {
    id: "shotgun",
    name: "CORN SHOTGUN",
    damage: 9,
    count: 7,
    spread: 0.2,
    speed: 11,
    cooldown: 0.75,
    ammoKey: "corn",
    ammoPerShot: 1,
    projectileSprite: "cornKernel",
    flashColor: "#ffe08a",
  },
  {
    id: "launcher",
    name: "COB LAUNCHER",
    damage: 90,
    count: 1,
    spread: 0.01,
    speed: 8,
    cooldown: 1.05,
    ammoKey: "cob",
    ammoPerShot: 1,
    projectileSprite: "cobRocket",
    splash: 2.4,
    flashColor: "#ff8844",
  },
];
